### refreshToken.http


### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los refresh tokens
GET {{baseUrl}}/refresk-token

### ================== RUTAS CON AUTENTICACIÓN ==================