
### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los roles
GET {{baseUrl}}/api/roles/public
Accept: application/json

### Obtener rol por ID
GET {{baseUrl}}/api/roles/1

### Crear un nuevo rol
POST {{baseUrl}}/api/roles/public
Content-Type: application/json

{
  "name": "Usuario",
  "is_active": "ACTIVE"
}

### Actualizar un rol
PATCH {{baseUrl}}/api/roles/public/1
Content-Type: application/json

{
  "name": "Super Administrator",
  "is_active": "ACTIVE"
}

### Eliminar un rol físicamente
DELETE {{baseUrl}}/api/roles/public/1

### Eliminar un rol lógicamente
DELETE {{baseUrl}}/api/roles/public/2/logic

### ================== RUTAS CON AUTENTICACIÓN ==================

### Obtener todos los roles (CON token)
GET {{baseUrl}}/api/roles
Authorization: Bearer {{$dotenv TOKEN}}

### Obtener rol por ID (CON token)
GET {{baseUrl}}/api/roles/1
Authorization: Bearer {{$dotenv TOKEN}}

### Crear un nuevo rol (CON token)
POST {{baseUrl}}/api/roles
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "name": "recepcionista",
  "is_active": "ACTIVE"
}

### Actualizar un rol (CON token)
PATCH {{baseUrl}}/api/roles/2
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "name": "usuario",
  "is_active": "ACTIVE"
}

### Eliminar un rol físicamente (CON token)
DELETE {{baseUrl}}/api/roles/2
Authorization: Bearer {{$dotenv TOKEN}}

### Eliminar un rol lógicamente (CON token)
DELETE {{baseUrl}}/api/roles/1/logic
Authorization: Bearer {{$dotenv TOKEN}}
