
### List appointments
GET {{baseUrl}}/api/appointment/public
Accept: application/json

### Get appointment by id (public)
GET {{baseUrl}}/api/appointment/public/1
Accept: application/json

### Create appointment
POST {{baseUrl}}/api/appointment/public
Content-Type: application/json

{
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-20T08:13:45.000Z",
  "consultation_reason": "Dolor abdominal persistente desde hace 3 días.",
  "status": "ACTIVE",
  "observations": "Paciente con leve malestar general."
}

### Update appointment
PUT {{baseUrl}}/api/appointment/public/1
Content-Type: application/json

{
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-22T10:30:00.000Z",
  "consultation_reason": "Actualización: el paciente presenta mejora pero requiere revisión.",
  "status": "ACTIVE",
  "observations": "Se recomienda seguimiento semanal."
}

### Delete appointment
DELETE {{baseUrl}}/api/appointment/public/1

// Peticiones con autenticación
### List appointments (protegido)
GET {{baseUrl}}/api/appointment
Authorization: Bearer {{$dotenv TOKEN}}

### Get appointment by id (protegido)
GET {{baseUrl}}/api/appointment/1
Authorization: Bearer {{$dotenv TOKEN}}

### Create appointment (protegido)
POST {{baseUrl}}/api/appointment
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-20T08:13:45.000Z",
  "consultation_reason": "Dolor abdominal persistente desde hace 3 días.",
  "status": "ACTIVE",
  "observations": "Paciente con leve malestar general."
}

### Update appointment (protegido)
PUT {{baseUrl}}/api/appointment/1
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-22T10:30:00.000Z",
  "consultation_reason": "Actualización: el paciente presenta mejora pero requiere revisión.",
  "status": "ACTIVE",
  "observations": "Se recomienda seguimiento semanal."
}

### Delete appointment (protegido)
DELETE {{baseUrl}}/api/appointment/1
Authorization: Bearer {{$dotenv TOKEN}}