### Appointment HTTP requests
#Base URL: http://localhost:3000/appointments
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTE4MzM0LCJleHAiOjE3NjA1MjE5MzR9.n85SFa4Z8A9Wu69GKzrVLWLjy4KOy9lhb_xtxfIM9_o
@baseUrl = http://localhost:3000
### List appointments
# Peticiones sin autenticación (token no requerido)
GET {{baseUrl}}/api/appointment/public
Accept: application/json

### Create appointment
# Peticiones sin autenticación (token no requerido)
POST {{baseUrl}}/api/appointment/public
Content-Type: application/json

{
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-20T08:13:45.000Z",
  "consultation_reason": "Dolor abdominal persistente desde hace 3 días.",
  "status": "ACTIVE",
  "observations": "Paciente con leve malestar general."
}


### Update appointment
# Peticiones sin autenticación (token no requerido)
PUT {{baseUrl}}/api/appointment/public/1
Content-Type: application/json

{
  "id": 1,
  "patient_id": 23,
  "doctor_id": 31,
  "appointment_datetime": "2025-10-22T10:30:00.000Z",
  "consultation_reason": "Actualización: el paciente presenta mejora pero requiere revisión.",
  "status": "ACTIVE",
  "observations": "Se recomienda seguimiento semanal."
}

### Delete appointment
# Peticiones sin autenticación (token no requerido)

DELETE {{baseUrl}}/api/appointment/public/1


### Get appointment by id

# Peticiones con autenticación
GET {{baseUrl}}/api/appointment
Authorization: Bearer {{token}}
