
### List prescriptions
GET {{baseUrl}}/api/prescriptions/public
Accept: application/json

### Peticiones con autenticación
GET {{baseUrl}}/api/prescriptions
Authorization: Bearer {{$dotenv TOKEN}}
