
### List prescription details
GET {{baseUrl}}/api/prescriptionDetail/public
Accept: application/json

### Peticiones con autenticación
GET {{baseUrl}}/api/prescriptionDetail
Authorization: Bearer {{$dotenv TOKEN}}