

// Peticiones sin autenticación
### Obtener todos los procedimientos (público)
GET {{baseUrl}}/api/procedure/public
Accept: application/json

### Obtener procedimiento por ID (público)
GET {{baseUrl}}/api/procedure/public/1
Accept: application/json

### Crear un nuevo procedimiento (publico)
POST {{baseUrl}}/api/procedure/public
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "appointment_id": 1,
  "procedure_code": "PROC-001",
  "procedure_name": "Limpieza dental",
  "description": "Limpieza y revisión general",
  "cost": 150000,
  "performed_date": "2025-10-14",
  "status": "ACTIVE"
}

### Actualizar un procedimiento
PUT {{baseUrl}}/api/procedure/public/21
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "appointment_id": 1,
  "procedure_code": "PROC-001",
  "procedure_name": "Limpieza dental profunda",
  "description": "Limpieza general con ultrasonido",
  "cost": 200000,
  "performed_date": "2025-10-14",
  "status": "ACTIVE"
}

### Eliminar un procedimiento (cambia estado a INACTIVE)
DELETE {{baseUrl}}/api/procedure/public/21
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json


// Peticiones con autenticación
###
GET {{baseUrl}}/api/procedure
Authorization: Bearer {{$dotenv TOKEN}}

### Obtener procedimiento por ID (con autenticación)
GET {{baseUrl}}/api/procedure/1
Authorization: Bearer {{$dotenv TOKEN}}

### Crear un nuevo procedimiento (con autenticación)
POST {{baseUrl}}/api/procedure
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "appointment_id": 1,
  "procedure_code": "PROC-001",
  "procedure_name": "Limpieza dental",
  "description": "Limpieza y revisión general",
  "cost": 150000,
  "performed_date": "2025-10-14",
  "status": "ACTIVE"
}

### Actualizar un procedimiento (con autenticación)
PUT {{baseUrl}}/api/procedure/1
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "appointment_id": 1,
  "procedure_code": "PROC-001",
  "procedure_name": "Limpieza dental profunda",
  "description": "Limpieza general con ultrasonido",
  "cost": 200000,
  "performed_date": "2025-10-14",
  "status": "ACTIVE"
}

### Eliminar un procedimiento (cambia estado a INACTIVE) (con autenticación)
DELETE {{baseUrl}}/api/procedure/21
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json